# Generated by Django 5.0.14 on 2025-10-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sequence', models.TextField()),
                ('sequence_type', models.CharField(choices=[('DNA', 'ADN'), ('RNA', 'ARN')], max_length=3)),
                ('transcription', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True)),
                ('gc_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
